// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 import 'firebase_options.dart';
// ...
await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
 );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5pgRHU59bIGgXNtRECZ57qaBQyVKVmTc',
    appId: '1:575035757817:web:3b48af388e0de390b5be28',
    messagingSenderId: '575035757817',
    projectId: 'lebeaumonde-ba7da',
    authDomain: 'lebeaumonde-ba7da.firebaseapp.com',
    storageBucket: 'lebeaumonde-ba7da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzM28AE3qm3NFZ54ViHcrPMF6jgT2VxRY',
    appId: '1:575035757817:android:2598a7e8753ceaafb5be28',
    messagingSenderId: '575035757817',
    projectId: 'lebeaumonde-ba7da',
    storageBucket: 'lebeaumonde-ba7da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFiT8GUqHANyXzvTiADwytlVgbXV3s5fg',
    appId: '1:575035757817:ios:4ffde3bf32dea6f1b5be28',
    messagingSenderId: '575035757817',
    projectId: 'lebeaumonde-ba7da',
    storageBucket: 'lebeaumonde-ba7da.appspot.com',
    iosClientId: '575035757817-jbt4pc84nkip1qnrq7cp8bvsm6l7ca53.apps.googleusercontent.com',
    iosBundleId: 'com.example.lebeaumonde',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFiT8GUqHANyXzvTiADwytlVgbXV3s5fg',
    appId: '1:575035757817:ios:4ffde3bf32dea6f1b5be28',
    messagingSenderId: '575035757817',
    projectId: 'lebeaumonde-ba7da',
    storageBucket: 'lebeaumonde-ba7da.appspot.com',
    iosClientId: '575035757817-jbt4pc84nkip1qnrq7cp8bvsm6l7ca53.apps.googleusercontent.com',
    iosBundleId: 'com.example.lebeaumonde',
  );
}
